
---
name: Build wishlist.txt

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Add build info
        run: |
            (
              echo ''
              echo '// Build Info:'
              echo '//   Job:      ${{ env.GITHUB_JOB }}'
              echo '//   Event:    ${{ env.GITHUB_EVENT_NAME }}'
              echo '//   Workflow: ${{ env.GITHUB_WORKFLOW }}'
              echo '//   Time:     ${{ steps.timestamp.outputs.now }}'
            ) >> ./src/_header.txt

      - name: Build
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: wishlist_latest
          path: build/wishlist.txt
          if-no-files-found: error
