
---
name: Build wishlist.txt

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Add build info
        run: |
            (
              echo ''
              echo "// Build Info:"
              echo "//   Job:      ${GITHUB_JOB}"
              echo "//   Event:    ${GITHUB_EVENT_NAME}"
              echo "//   Workflow: ${GITHUB_WORKFLOW}"
              echo "//   Time:     ${{ steps.timestamp.outputs.now }}"
              echo ''
              echo ''
            ) >> ./src/_header.txt

      - name: Build
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: wishlist_latest
          path: build/wishlist.txt
          if-no-files-found: error
