
---
name: Build Latest Wishlist.txt

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Build
        run: make

      - uses: actions/upload-artifact@v3
        with:
          name: wishlist_latest
          path: wishlist.txt
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: wishlist_latest

      - name: Get current time
        id: timestamp
        run: echo "::set-output name=now::$(date +'%Y-%m-%dT%H:%M:%S')"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: .
          default_author: github_actor
          message: GitHub Actions release - ${{ steps.timestamp.outputs.now }}
          new_branch: release

      # - uses: actions/download-artifact@v3
      #   with:
      #     name: wishlist_latest

      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     title: "Latest Build"
      #     files: |
      #       wishlist.txt
