
---
name: (Release) wishlist

on:
  workflow_dispatch:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: wishlist_latest

      - name: Get current time
        id: timestamp
        run: echo "::set-output name=now::$(date +'%Y-%m-%dT%H:%M:%S')"

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: wishlist.txt grrbearr.txt --force
          default_author: github_actor
          message: GitHub Actions release - ${{ steps.timestamp.outputs.now }}
          push: origin release --set-upstream --force
          new_branch: release
