
---
name: Build Latest Wishlist

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '30 2,10,18 * * *'

jobs:
  build-wishlist:
    uses: ./.github/workflows/build.yml
  release-wishlist:
    needs: build-wishlist
    uses: ./.github/workflows/release.yml
