
---
name: Build & Release Latest Wishlist

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron:  '30 11 * * *' # 06:30 AM
    - cron:  '0 18 * * *'  # 01:00 PM
    - cron:  '10 1 * * *'  # 08:10 PM

jobs:
  build-wishlist:
    uses: ./.github/workflows/build.yml
  release-wishlist:
    needs: build-wishlist
    uses: ./.github/workflows/release.yml
